name: Build Geode Mod

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Geode CLI
      run: brew install geode-sdk/geode/geode-cli

    - name: Install Geode SDK
      run: |
        mkdir -p $HOME/geode-sdk
        curl -L https://api.geode-sdk.org/sdk/latest -o geode-sdk.zip
        unzip geode-sdk.zip -d $HOME/geode-sdk

    - name: Set Geode SDK Path
      run: echo "GEODE_SDK=$HOME/geode-sdk" >> $GITHUB_ENV

    - name: Build Geode Mod
      run: geode build

    - name: Find .geode file
      id: find_geode
      run: |
        GEODE_FILE=$(find . -type f -name "*.geode" | head -n 1)
        if [ -z "$GEODE_FILE" ]; then
          echo "No .geode file found!"
          exit 1
        fi
        echo "GEODE_FILE=$GEODE_FILE" >> $GITHUB_ENV
        echo "Geode file found: $GEODE_FILE"

    - name: Upload Geode Mod Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Geode Mod
        path: ${{ env.GEODE_FILE }}
        if-no-files-found: error
